[build]
  base    = ""
  publish = "."

[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/daily-result"
  to   = "/daily-result.html"
  status = 200

[[redirects]]
  from = "/ticket-booking"
  to   = "/ticket-booking.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
